/**
 * 新手引导步骤配置
 *
 * 每个步骤字段说明：
 * - id:              唯一标识
 * - key:             步骤键名（用于持久化）
 * - page:            该步骤所在页面 key（与 activePage 对应）
 * - targetSelector:  要高亮的 DOM 元素选择器
 * - title:           标题
 * - content:         说明文案
 * - placement:       提示框位置 (top / bottom / left / right / center)
 * - actionType:      交互类型
 *     highlight-only   只高亮展示
 *     click-target     需要点击目标元素
 *     navigate         需要切换页面
 * - nextCondition:   进入下一步的条件 (auto / click / navigate)
 * - isOptional:      是否可选步骤
 * - requiredFeature: 需要解锁的功能（对应 FEATURE_LEVEL_MAP 的 key），未解锁则跳过
 * - sortOrder:       排序序号
 */

const tutorialSteps = [
  {
    id: 1,
    key: 'welcome',
    page: 'overview',
    targetSelector: null,
    title: '欢迎来到农场！',
    content: '这是你的专属农场，在这里你可以种植作物、养殖动物、加工商品赚取收益。让我带你快速了解各个功能吧！',
    placement: 'center',
    actionType: 'highlight-only',
    nextCondition: 'click',
    isOptional: false,
    requiredFeature: null,
    sortOrder: 1,
  },
  {
    id: 2,
    key: 'statusbar',
    page: 'overview',
    targetSelector: '.farm-statusbar',
    title: '资源总览',
    content: '这里显示你的核心资源：💰金币余额、⭐等级、🌾地块数量和当前天气。随时关注它们的变化。',
    placement: 'bottom',
    actionType: 'highlight-only',
    nextCondition: 'click',
    isOptional: false,
    requiredFeature: null,
    sortOrder: 2,
  },
  {
    id: 3,
    key: 'stats',
    page: 'overview',
    targetSelector: '.farm-stat-card',
    title: '仪表盘',
    content: '仪表盘展示当前农场状态——余额、地块使用情况、种植中和可收获的作物数量。',
    placement: 'bottom',
    actionType: 'highlight-only',
    nextCondition: 'click',
    isOptional: false,
    requiredFeature: null,
    sortOrder: 3,
  },
  {
    id: 4,
    key: 'quick-actions',
    page: 'overview',
    targetSelector: '.farm-overview-actions',
    title: '快捷操作栏',
    content: '这里是快捷操作区，可以一键收获、浇水、施肥。当作物成熟时，这里会出现收获按钮。',
    placement: 'bottom',
    actionType: 'highlight-only',
    nextCondition: 'click',
    isOptional: false,
    requiredFeature: null,
    sortOrder: 4,
  },
  {
    id: 5,
    key: 'plot-grid',
    page: 'overview',
    targetSelector: '.farm-plot-grid',
    title: '你的农田',
    content: '这些是你的地块。空地可以种植作物，正在生长的作物需要定期浇水。点击地块可以查看详情和操作。',
    placement: 'top',
    actionType: 'highlight-only',
    nextCondition: 'click',
    isOptional: false,
    requiredFeature: null,
    sortOrder: 5,
  },
  {
    id: 6,
    key: 'go-plant',
    page: 'overview',
    targetSelector: '[data-tutorial="nav-plant"]',
    title: '去种植',
    content: '点击侧栏的「种植」进入种植页面，选择作物并种到空地上。这是你赚取第一桶金的起点！',
    placement: 'right',
    actionType: 'navigate',
    navigateTo: 'plant',
    nextCondition: 'navigate',
    isOptional: false,
    requiredFeature: null,
    sortOrder: 6,
  },
  {
    id: 7,
    key: 'plant-page',
    page: 'plant',
    targetSelector: '.farm-card',
    title: '选择作物',
    content: '这里列出了所有可种植的作物。每种作物有不同的种子价格、生长时间和收益。新手推荐先种小麦或土豆，投入低、见效快！',
    placement: 'bottom',
    actionType: 'highlight-only',
    nextCondition: 'click',
    isOptional: false,
    requiredFeature: null,
    sortOrder: 7,
  },
  {
    id: 8,
    key: 'go-overview-back',
    page: 'plant',
    targetSelector: null,
    title: '回到总览',
    content: '种下作物后，回到总览页面查看生长状态。作物需要定期浇水，成熟后记得收获！',
    placement: 'center',
    actionType: 'navigate',
    navigateTo: 'overview',
    nextCondition: 'navigate',
    isOptional: false,
    requiredFeature: null,
    sortOrder: 8,
  },
  {
    id: 9,
    key: 'sidebar',
    page: 'overview',
    targetSelector: '.farm-sidebar',
    title: '功能导航',
    content: '左侧导航栏包含所有功能模块。随着等级提升，更多功能会逐步解锁。',
    placement: 'right',
    actionType: 'highlight-only',
    nextCondition: 'click',
    isOptional: false,
    requiredFeature: null,
    sortOrder: 9,
  },
  {
    id: 10,
    key: 'market-intro',
    page: 'overview',
    targetSelector: '[data-tutorial="nav-market"]',
    title: '市场系统',
    content: '市场价格会实时波动！学会观察趋势，在价格高点出售可以获得更多收益。达到2级即可解锁。',
    placement: 'right',
    actionType: 'highlight-only',
    nextCondition: 'click',
    isOptional: false,
    requiredFeature: null,
    sortOrder: 10,
  },
  {
    id: 11,
    key: 'shop-intro',
    page: 'overview',
    targetSelector: '[data-tutorial="nav-shop"]',
    title: '商店',
    content: '在商店购买种子、肥料、农药等道具。合理使用道具可以加速作物生长、提高产量。',
    placement: 'right',
    actionType: 'highlight-only',
    nextCondition: 'click',
    isOptional: false,
    requiredFeature: null,
    sortOrder: 11,
  },
  {
    id: 12,
    key: 'warehouse-intro',
    page: 'overview',
    targetSelector: '[data-tutorial="nav-warehouse"]',
    title: '仓库',
    content: '仓库可以暂存收获的作物，等市场价格好时再出售。但要注意保质期，过期会损失哦！',
    placement: 'right',
    actionType: 'highlight-only',
    nextCondition: 'click',
    isOptional: false,
    requiredFeature: null,
    sortOrder: 12,
  },
  {
    id: 13,
    key: 'tasks-intro',
    page: 'overview',
    targetSelector: '[data-tutorial="nav-tasks"]',
    title: '每日任务',
    content: '完成每日任务可以获得额外奖励和经验值，帮助你更快升级解锁新功能！',
    placement: 'right',
    actionType: 'highlight-only',
    nextCondition: 'click',
    isOptional: false,
    requiredFeature: null,
    sortOrder: 13,
  },
  {
    id: 14,
    key: 'treefarm-intro',
    page: 'overview',
    targetSelector: '[data-tutorial="nav-treefarm"]',
    title: '树场',
    content: '树场是长线投资——种下果树或木材树，定期收获果实或一次伐木获取大量资源。达到5级解锁！',
    placement: 'right',
    actionType: 'highlight-only',
    nextCondition: 'click',
    isOptional: true,
    requiredFeature: 'treefarm',
    sortOrder: 14,
  },
  {
    id: 15,
    key: 'finish',
    page: 'overview',
    targetSelector: null,
    title: '准备就绪！',
    content: '基础教学完成！现在去种下你的第一株作物吧。随时可以点击右上角的「📖」按钮重新查看引导。祝你丰收！🌾',
    placement: 'center',
    actionType: 'highlight-only',
    nextCondition: 'click',
    isOptional: false,
    requiredFeature: null,
    sortOrder: 15,
  },
];

export default tutorialSteps;
